### ISSUE TITLE
有个小问题，在vue中使用时，页面往回跳转（从文章页码跳转到主页）后会显示目录索引，这个可以优化吗？

### ISSUE THREAD

**Issue by JiageWang** [yaohaixiao/outline.js#21]

**Comment by yaohaixiao** [comment]
不好意思，现在才回复，针对你的情况，新版本的 outline.js 是支持隐藏菜单的和工具栏的。

在离开文章页面的时候 beforeDestroy() 方法中调用 destroy() 方法即可啊，新老版本都有这个方法的
