### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by whitebearcode** [yaohaixiao/outline.js#36]
你好，这里有一个问题。
文章内容中存在h1-h6标签
目录导读也可以准确识别
但在阅读模式中只获取到了h2和h4标签
这个问题请问如何解决呢。

**Comment by whitebearcode** [comment]
感觉是内容获取问题，有时候是能获取到标签，但获取不到H1-6标签下的其他内容（如文字和图片等

**Comment by yaohaixiao** [comment]
不好意思啊，最近比较忙，才看到你的问题，你可以贴图指出具体的问题(只读模式只获取了h2和h4)吗？

**Comment by whitebearcode** [comment]
![图一](https://i.ibb.co/Byy9NY1/Screenshot-2023-10-31-20-09-59-657-com-android-chrome-edit.jpg)
![图二](https://i.ibb.co/bNXgvFG/Screenshot-2023-10-31-20-09-24-712-com-android-chrome-edit.jpg)
像这样，目录树可以完整获取到，但阅读模式却获取不全

**Comment by whitebearcode** [comment]
这个问题挺奇怪的，有时候不同格式能够获取到的内容还不一样

**Comment by whitebearcode** [comment]
比如只写了H1和文字内容，只显示文字内容不显示H1标签的内容

**Comment by yaohaixiao** [comment]
已修复阅读模式正文显示不全的问题，你获取最新版本验证一下，如果已经修复，这个问题就可以关闭了

**Comment by yaohaixiao** [comment]
问题已经修复，关闭该问题
