### ISSUE TITLE
有没有更新的方法

### ISSUE THREAD

**Issue by nickolboy** [yaohaixiao/outline.js#38]
例如我正在编辑文章，这时候新加入了标题，我想要实时更新目录

**Comment by yaohaixiao** [comment]
可以使用 reload() 方法，这个方法就是用于整体更新界面的。由于目前 github push 代码总是超时，目前仓库的代码不是最新的，但 npmjs.com 的包是最新的，你使用 3.30.3 版本，reload() 方法是可以用的，之前版本 reload() 方法有BUG

**Comment by yaohaixiao** [comment]
3.32.0 添加了 refresh() 方法
