### ISSUE TITLE
你好，请问vue下节点选择

### ISSUE THREAD

**Issue by sunkingsss** [yaohaixiao/outline.js#4]
<div id="guideBook" class="guideBook" v-html="content"></div>

在v-html的div中放入正文，在autocjs对象中没有看到对应的chapters和headings,这个该怎么解决
![image](https://user-images.githubusercontent.com/17444344/68374954-d2a9b380-0180-11ea-9573-7b026f735e47.png)

**Comment by yaohaixiao** [comment]
这个因为你的正文是动态绘制的，不知到是页面 mounted 完了绘制的，还是直接在 <template></template>中使用 v-html绘制的。

如果是直接在 <template> 标签中绘制的，在 mounted() 方法中

```js
mounted() {
    this.$nextTick(() => {
     // 确保正文的 DOM 已经绘制完毕
      setTimeout(() => {
        new AutocJS(options)
        // 或者新版的 
        new Outline(options)
      }, 150)
    })
  }
```
