### ISSUE TITLE
兄弟，对于不支持的低版本的浏览器，能不能直接console.log说下不支持低版本浏览器？

### ISSUE THREAD

**Issue by nottellyou** [yaohaixiao/outline.js#43]
兄弟，对于不支持的低版本的浏览器，能不能直接console.log说下不支持低版本浏览器？
现在是直接抛错，不太好。抛错后，可能会影响后面JS的正常运行。
现在还在用chrome54内核的路过。

**Comment by yaohaixiao** [comment]
可以的，不过你可以把报错提示贴一下吗，也许我兼容起来会比报错更简单些

**Comment by nottellyou** [comment]
![image](https://github.com/yaohaixiao/outline.js/assets/8598743/2f1b6095-eb93-492f-adc2-989986205e3a)
![image](https://github.com/yaohaixiao/outline.js/assets/8598743/980a3221-e35f-4807-b215-5c82c87fff06)
![image](https://github.com/yaohaixiao/outline.js/assets/8598743/947223c0-2801-4d05-b7d0-a1137b3765ad)
麻烦看下图片，我会的JS不多。

**Comment by yaohaixiao** [comment]
已经发布了 3.32.3 修复了这个问题，应该是可选链操作符语法导致的，你更新试试，没问题就关闭这个 issue

**Comment by nottellyou** [comment]
兄弟，是不是用这个项目目录里的两个文件就可以了： outline.min.js、 outline.min.css 

建议：给outline.min.js加个版本号，我没看到版本号

应该没有解决低版本chrome浏览器（Chromium 54.0.2840.99）报错的问题，是不是还有其它不兼容的地方呢？示例地址：http://biji.sebcxy.com/forum.php?mod=viewthread&tid=337&extra=page%3D1
