### ISSUE TITLE
大哥，报告个bug

### ISSUE THREAD

**Issue by nottellyou** [yaohaixiao/outline.js#44]
1、bug：样式与dz论坛的点评冲突了。
     地址：http://biji.sebcxy.com/forum.php?mod=viewthread&tid=49&extra=
    
![image](https://github.com/yaohaixiao/outline.js/assets/8598743/9d2e8ed2-968d-448b-9189-d5baa7783754)

2、建议：给outline.min.js加个版本号，我没看到版本号
     是不是用这个项目目录里的两个文件就可以了： outline.min.js、 outline.min.css。我一直这样用。

**Comment by yaohaixiao** [comment]
感谢你的反馈，不过我没有太看明白你的问题，我的 CSS 样式应该没有跟你的样式冲突。

我看你的这个站点的演示界面的点评样式不对，好像是因为它的外曾 DIV class="cm"  其余都是 class="t_f"

加版本号目前是不会处理的，你可以调用脚本的时候 <script src="path/to/outline.min.js?random=随机字符串">

**Comment by nottellyou** [comment]
大哥，你用一个低版本的浏览器和一个高版本的浏览器看连接中“点评”的样式。

我用chrome54/chrome58访问“点评”样式是正常的，但用chrome102访问“点评”样式就不正常了。


我说的版本号是在outlime.js内加一个变量：var version='3.33.2';这样。

**Comment by nottellyou** [comment]
我用chrome60就正常，估计outlime.js最低支持的chrome版本为60
