### ISSUE TITLE
你好，在浏览器Chromium 60.0.3112.113版本上，点击文章目录导航却不跳转，这算是bug吗？

### ISSUE THREAD

**Issue by nottellyou** [yaohaixiao/outline.js#45]
你好，在浏览器Chromium 60.0.3112.113版本上，点击文章目录导航却不跳转，这算是bug吗？

或许说，使用了新技术不支持老旧的chrome内核？

**Comment by nottellyou** [comment]
在Chromium 59.0.3071.115版本上会报错，有没有方法让它不报错呢？应该是版本太老，不支持吧。

**Comment by yaohaixiao** [comment]
不好意思，才看到，能将你的报错截图展示一下吗

**Comment by nottellyou** [comment]
问题1：在chrome60上不报错，就是不执行点击锚点跳转动作
问题2：在chrome59上报错：
![PixPin_2024-05-16_08-49-56](https://github.com/yaohaixiao/outline.js/assets/8598743/416d1def-19e9-4b5b-b378-991b3735eb62)

**Comment by yaohaixiao** [comment]
感谢你的反馈，我会尽快修复这个问题的

**Comment by yaohaixiao** [comment]
看你的截图应该是 ES6 扩展运算符（spread）语法的问题，我 3.38.1 修复了编译后还保留扩展运算符语法的问题，你获取最新的看看问题解决没有

**Comment by nottellyou** [comment]
问题1：在chrome60上不报错，就是不执行点击锚点跳转动作，是什么原因呢？
问题2：用最新版已经解决报错问题了。

**Comment by yaohaixiao** [comment]
60上还是不能跳转吗？

**Comment by nottellyou** [comment]
是的，在chrome60上不报错，也不执行点击锚点跳转动作。

估计这个问题比较难查，要是报错的话，还可以追踪。

**Comment by yaohaixiao** [comment]
好的，我再看看代码，看是不是使用了浏览器不支持的 API

**Comment by nottellyou** [comment]
辛苦了

**Comment by yaohaixiao** [comment]
defaults.scrollElement = 'body'
设置一下 scrollElement 参数为 body，我用旧版本的 chrome 测试了，由于我的配置模式 defaults.scrollElement = 'html,body' 老的内核不支持设置 html 元素的 scrollTop 导致的

**Comment by nottellyou** [comment]
厉害，确实是 这个问题。
感谢提供这么好用的组件。
