### ISSUE TITLE
Uncaught TypeError: this.calculateStickyHeight is not a function

### ISSUE THREAD

**Issue by RhythmPony** [yaohaixiao/outline.js#48]
每当窗口resize的时候都会出现错误信息，我想了很久都没有解决，虽然不影响正常使用，希望大神能帮忙分析一下
![image](https://github.com/yaohaixiao/outline.js/assets/81352426/c6051684-657d-459e-aad5-10071255ef0f)

**Comment by yaohaixiao** [comment]
可以把你的初始化配置贴出来吗

**Comment by RhythmPony** [comment]
> 可以把你的初始化配置贴出来吗

我的配置是这样的
![image](https://github.com/yaohaixiao/outline.js/assets/81352426/43a974c6-0c73-4de2-8211-ec2223b1ace1)

**Comment by yaohaixiao** [comment]
我本地测试过，没有报出你这个错误啊，另外你的配置中的 closeOnClickModal 和 showNavModalFirst 在配置了 position = 'sticky' 和 hasToolbar 后是无效的，你可以尝试我的配置，当然根据你的需要其调整一下：

`const defaults = Outline.DEFAULTS
        let outline

        defaults.position = 'sticky'
        defaults.stickyHeight = 86
        defaults.parentElement = '#aside'
        defaults.scrollElement = 'body'
        defaults.homepage = '../index.html'
        outline = new Outline(defaults)`

如果有可以访问的DEMO地址最好，因为我无法重新你的错误

**Comment by RhythmPony** [comment]
[文章地址](https://nixaix.com/article/?num=21)，请帮我看看

**Comment by yaohaixiao** [comment]
我看了下，应该不是BUG，是你的配置有问题，不能 reload()，reload() 后使用的默认配置 position='relative'，你用那个版本的，用最新版本的试试

![企业微信截图_17190192938684](https://github.com/yaohaixiao/outline.js/assets/1411473/91b5a524-0b1e-48c3-a3e1-a1364fe6d905)
![企业微信截图_17190193507078](https://github.com/yaohaixiao/outline.js/assets/1411473/17642e2d-98cc-4fc8-8b2b-6fbde5fa3387)

你看我本地用的最新版本的没有这个问题，老的版本以前的 reload() 方法有点问题，建议你用最新版本的，或者配置完后，不要使用 reload()

并且建议你使用 sticky 定位显示，设置 stickyHeight 参数，将值设置为你的固定位置菜单的高度，以便这个文章导航菜单都可以显示，目前你的菜单被挡住了，就是没有设置 stickyHeight 导致的
