### ISSUE TITLE
没有目录树的情况下只能点击抵达底部

### ISSUE THREAD

**Issue by whitebearcode** [yaohaixiao/outline.js#50]
没有目录树的情况下只能点击向下的按钮抵达底部，到底部的时候向上返回顶部的按钮出不来

**Comment by whitebearcode** [comment]
还有就是独立目录树模式下，点击目录树第一次会出不来

**Comment by yaohaixiao** [comment]
感谢你的反馈，能截图说明以下吗？

**Comment by whitebearcode** [comment]
就是独立目录导航，点击导航目录按钮不是应该显示出来文章目录吗，然而点击后会直接全部隐藏，啥都没有了

**Comment by yaohaixiao** [comment]
你的配置可以贴出来看看吗，或者给个演示地址我看看

**Comment by whitebearcode** [comment]
可能是我的站点css与outline冲突，你说的配置如下:
(function(){
    const defaults = Outline.DEFAULTS
    let outline

    defaults.position = 'relative'
    defaults.articleElement = '#article'
    defaults.homepage = './index.html'
    // Outline.DEFAULTS 是对象，应用类型的
    outline = new Outline(defaults)
  })()
