### ISSUE TITLE
Vue2中这个报错怎么解决

### ISSUE THREAD

**Issue by valklyrss** [yaohaixiao/outline.js#51]
ERROR  Failed to compile with 1 error                                                                          17:02:39

 error  in ./node_modules/@yaohaixiao/outline.js/outline.js

Module parse failed: Unexpected token (347:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }
|     }
>     if (tools?.length > 0) {
|       buttons.push(...tools)
|     }

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/blog/detail.vue?vue&type=script&lang=js 12:38-79
 @ ./src/views/blog/detail.vue?vue&type=script&lang=js
 @ ./src/views/blog/detail.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.8.16:81&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by yaohaixiao** [comment]
你是直接引用的我的  ES6 模块吗？如果是，添加以下这个插件:@babel/plugin-transform-optional-chaining

`
/**
 * babel.config.js - Babel 工程配置
 * =============================================================
 * Created By: Yaohaixiao
 * Update: 2023.2.27
 */
module.exports = {
  presets: [['@babel/preset-env']],
  plugins: [
    // 配置“可选链操作符”（babel插件）
    '@babel/plugin-transform-optional-chaining',
    '@babel/plugin-transform-spread',
    '@babel/plugin-transform-object-rest-spread'
  ],
  assumptions: {
    arrayLikeIsIterable: true
  }
}
`

**Comment by yaohaixiao** [comment]
应该可以确定是你的项目没有配置 配置“可选链操作符”（babel插件） 的解析插件的问题了
