### ISSUE TITLE
标题中带括号会被过滤

### ISSUE THREAD

**Issue by valklyrss** [yaohaixiao/outline.js#54]
![image](https://github.com/user-attachments/assets/07023b5d-5848-4804-80e6-8d27f180659c)
在getChaptersByHeadings.js的第97行
![image](https://github.com/user-attachments/assets/02ac4b0e-cd23-465f-8a65-4559ca118c07)
![image](https://github.com/user-attachments/assets/7106140f-9be8-4b25-a47a-f33bdd0573d4)

**Comment by yaohaixiao** [comment]
不好意思，感谢反馈，问题是在 getChapters.js 中，已经修复了 3.39.3
