### ISSUE TITLE
博主，我找到outline.js和dzx3.5点评冲突的地方了？麻烦修正下

### ISSUE THREAD

**Issue by nottellyou** [yaohaixiao/outline.js#55]
![image](https://github.com/user-attachments/assets/c7340914-a4c2-4d37-aca9-c8d002574fdf)

看红色框框起来的地方，是outline.js加载后，将h3原有的class给删除了，然后加上自己的样式。

博主，能不能优化一下，只添加class，不要去掉原来的样式？

测试地址：http://biji.sebcxy.com/forum.php?mod=viewthread&tid=378&extra=page%3D1

**Comment by yaohaixiao** [comment]
不好意思，才看到啊，996 害死人啊

**Comment by yaohaixiao** [comment]
已经修复 使用 3.39.2 版本
